### ISSUE TITLE
Use with "managed = False"

### ISSUE THREAD

**Issue by spabinger** [tolomea/django-auto-prefetch#119]
### Description

Hi,

thanks for the nice package.

How would I use it when setting "managed = False" in the Meta information of a model? In this case, no migrations are detected by Django. Could you please provide an example configuration?

Thanks,
Stephan

    class Meta:
        managed = False
        db_table = 'MyTable'

**Comment by tolomea** [comment]
I haven't worked with managed = False tables. This package is purely queryset stuff, nothing changes in the DB when you enable it. There are typically migrations but only because Django creates no-op migrations for meta info changes.  What problem are you experiencing?

**Comment by adamchainz** [comment]
> There are typically migrations but only because Django creates no-op migrations for meta info changes.

Yes, I don't expect there to be any issue with `managed = False`.

If you can try it out and report @spabinger , we could tweak the docs to say the migration isn't necessary with `managed = False`.

**Comment by spabinger** [comment]
Thanks for the reply!

I was just wondering because the documentation says 

    Run python manage.py makemigrations to generate migrations, which set the Meta.base_manager_name option (docs) 
    to prefetch_manager on every model you’ve converted. This is to make sure auto-prefetching happens on related
    managers. If you instead set Meta.base_manager_name on your models, make sure it inherits from
    auto_prefetch.Manager

Do I need to set this manually?

Thanks.

**Comment by adamchainz** [comment]
No, this is a migration that does not affect the DB:

> This package is purely queryset stuff, nothing changes in the DB when you enable it.

It's already set in the model class by inheriting from `auto_prefetch.Model`. So there's no need for a migration when `managed = False`.

Please try it out and let us know.

**Comment by spabinger** [comment]
Hi,

I could finally test it and unfortunately it does not seem to work.

When accessing the list view, I still see a query for each row for {{ xy.get_all_aas }} .

Do you know what is missing?
Thanks,
Stephan



My models:

    class XY(auto_prefetch.Model):
      id = models.AutoField(db_column='XY_ID', primary_key=True)
      name = models.CharField(db_column='Name', max_length=200, blank=True, null=True)
    
      def get_all_aas(self):
        for aa in self.aa_set.all():
          print(aa)
    
      class Meta:
        managed = False
        db_table = 'XY'

    class AA(auto_prefetch.Model):
      xy = auto_prefetch.ForeignKey(XY, on_delete=models.CASCADE, db_column='XY_ID')
    
      class Meta:
        managed = False
        db_table = 'AA'


My view:

    class XYListView(LoginRequiredMixin, ListView):
      model = XY   
      template_name = 'xy_list_view.html'
      context_object_name = 'xy_list'

**Comment by adamchainz** [comment]
The line `self.aa_set.all()` is using the `ManyToManyField`’s related manager (`aa_set`) to construct a `QuerySet` on each loop (`.all()`). django-auto-prefetch does not touch `ManyToManyField`, so it cannot help you with that query.

If you do:

```
for aa in AA.objects.filter(...):
    print(aa.xy)
```

You should see that `auto_prefetch.ForeignKey` causes the `.xy` lookup to do a single query for all the `AA`s, rather than one per loop.

**Comment by tolomea** [comment]
In general the package only works for querys that happen on attribute access e.g. `aa.xy` it doesn't work for anything queryset like, so if there's `all`, `filter`, `order_by` etc then you still need to do prefetching manually.

**Comment by spabinger** [comment]
Thanks a lot for the explanation and the great package!

Best,
Stephan
