### ISSUE TITLE
Reverse manager of model doesn't auto-prefetch

### ISSUE THREAD

**Issue by tserrien** [tolomea/django-auto-prefetch#263]
### Python Version

3.11.0

### Django Version

4.2.4

### Package Version

1.7.0

### Description

I've created a small project to benchmark, where the reverse relationships don't work as expected.
I have the following models:

```python
# models.py
import auto_prefetch
from django.db import models
from django.utils.timezone import now

class Post(auto_prefetch.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = "Posts"


class Comment(auto_prefetch.Model):
    created_on = models.DateTimeField(default=now)
    body = models.TextField(max_length=1000)
    owner = auto_prefetch.ForeignKey(
        Commenter, on_delete=models.DO_NOTHING, related_name="comments"
    )
    posted_under = auto_prefetch.ForeignKey(
        Post, on_delete=models.DO_NOTHING, related_name="comments"
    )

    class Meta(auto_prefetch.Model.Meta):
        verbose_name = "Comments"
```

and the following test:
```python
# test_models.py
import pytest

from mixer.backend.django import mixer

from pytest_django.asserts import assertNumQueries
from ..models import Comment, Post

pytestmark = pytest.mark.django_db

def test_reverse():
    mixer.cycle(100).blend(Post)
    mixer.cycle(1500).blend(Comment, posted_under=mixer.SELECT)

    posts = Post.objects.all()

    with assertNumQueries(2):    # actual: 101
        for post in posts:
            comments = post.comments.all()
            for comment in comments:
                print(comment.created_on)
```
I'd expect 2 queries to be executed, 1 for actually executing `Post.object.all()` when the outer loop is called, 1 more to fetch `comments`.

The expected behaviour simulated with django's `prefetch_related` works as expected:
```python
    posts = Post.objects.prefetch_related("comments")
    with assertNumQueries(2):
        for post in posts:
            for comment in post.comments.all():
                print(comment.created_on)
```

Further details:
- No manager has been implemented for either model
- Tests for forward relationships work with the current implementation of the models
- pytest 7.4.0 and pytest-django 4.5.2 are the testrunners
- Full project can be made available
- Migrations were made for all models before tests were run

Edit: added `python` tag to code-blocks to improve readability

**Comment by tolomea** [comment]
It does not prefetch 2 many relations.

One of the design goals was to minimise the chance of it accidentally doing
substantially more DB work than if it hasn't been used. Crossing 2 many
relations leads to increasing numbers of rows which I felt was dangerous.

**Comment by tserrien** [comment]
Thank you for the quick answer! The first line of the readme lead me to assume it'd work on reverse FK relations as well, but understand the reasoning. Love the package, really great to use! :)

**Comment by tolomea** [comment]
Looking at it now I see that wording is a little ambiguous. It supports the
reverse side of one2one because those don't have the risk of increasing
numbers of rows.
