### ISSUE TITLE
Is it possible to use this without migrations?

### ISSUE THREAD

**Issue by YPCrumble** [tolomea/django-auto-prefetch#271]
### Description

I love the idea of this library - thank you for maintaining it!

The idea of having to run a migration for something like this sounds very risky...even if it doesn't change the database. Is there a way to use this without requiring a migration?

**Comment by adamchainz** [comment]
Unfortunately not, Django requires a migration for changing `base_manager_name`. I would reassure you though that the migrations are very low risk, they will run instantly and can be reversed easily.
