### ISSUE TITLE
Is it possible to run a custom `get_queryset` method with django-auto-prefetch?

### ISSUE THREAD

**Issue by nickmccullum** [tolomea/django-auto-prefetch#275]
### Python Version

3.10

### Django Version

4.2.6

### Package Version

1.7.0

### Description

I am trying to integrate `django-auto-prefetch` with a Django project that has a soft deletion framework. 

This doesn't work (i.e., it uses the regular Django query functionality.

```python
import auto_prefetch


class NotDeletableManager(auto_prefetch.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(deleted_at__isnull=True)
```
any tips?

**Comment by tolomea** [comment]
I'm going to need more detail about your current setup.
Is the soft deletion thing a library or just in the project?
How is it enabled / used at present?
In what contexts are you getting the full results instead of the soft
deletion filtered ones?

**Comment by tolomea** [comment]
That all sounds like it could be expected.
It's common that adding auto prefetch doesn't change perf rec results.
Anywhere you are doing perf rec I expect you have already also added
appropriate select/prefetch_related calls. With those in place auto
prefetch had nothing to do in those cases.
In the second case you are loosing the soft delete filtering which will
change your pref rec output, although probably not the number of queries,
just the details of the queries.

**Comment by tolomea** [comment]
Glad I could help
