### ISSUE TITLE
Can't get started?

### ISSUE THREAD

**Issue by iamjameswalters** [tolomea/django-auto-prefetch#339]
### Python Version

3.12.6

### Django Version

4.2.16

### Package Version

1.10

### Description

Hi there, 

I'm taking a crack at migrating an existing project to django-auto-prefetch, but after following the steps in the README, it seems nothing at all has changed? If I remove one of my own `.prefetch_related()` calls, the N+1 shows up.

There are some things that may be affecting my setup here--mainly that I'm using [mssql-django](https://github.com/microsoft/mssql-django) and I don't know if special support is required there?--but I really don't know where to begin.

I guess the crux of it is that those initial migrations tell Django to use auto_prefetch's own model managers. Where are those migrations actually being made? Is that data stored somewhere that I can check to see if the changes have actually been made? Or does Django load the migrations each time it runs to see 'soft' (non-schema) changes made by the migrations?

**Comment by iamjameswalters** [comment]
Update: I decided to try and rule out the possibility that mssql-django is a problem. I created a new SQLite DB, added some test data, and I still see the issue. Here is the `get_queryset()` method from the view I'm testing with:

```python
    def get_queryset(self):
        object_list = models.Client.objects.filter(
            Q(client_type__exact=self.client_type)
        )
        return object_list#.prefetch_related("systems")
 ```
 
 Commenting out that prefetch_related causes the N+1 to surface.

**Comment by tolomea** [comment]
It will be so nice when this thing is eventually merged into Django proper.

You want to make sure that auto_prefetch is in `Client.objects.all().__class__.__mro__` (the all is necessary to get from the manager to the queryset) and in `Client.systems.__class__.__mro__`.

I notice you have pluralized "systems" what the relationship between systems and clients?

Auto prefetch only applies to "to one" situations, so when systems is a ForeignKey on Client or a OneToOne on either Client or... System.

If it's a ForeignKey on System pointing at Client then Auto prefetch won't get involved.

It's mostly intended for the situation where you are doing
```
for city in City,objects.all():
    print(city.name, city.country.name) # fetching country per city
```
it doesn't help with
for country in Country.objects.all():
    for city in country.cities.all(): # fetching cities per country
        print(city.name, country.name)
```
the rationale being that the second case could lead to an explosion in the number of rows being fetched while the first case provably can't.

**Comment by iamjameswalters** [comment]
Well, I may have chosen an unfortunate example to test with, since "systems" is a ManyToManyField, which if I'm reading the README right, isn't helped by auto_prefetch?

So it will not handle nested loops over [related managers](https://docs.djangoproject.com/en/5.1/topics/db/queries/#related-objects), is that right? The first view I went to check after setting this up is one with a great deal of:

```python
for y in x.y_set:
    for z in y.z_set:
        print(z)
```

**Comment by tolomea** [comment]
No it won't help with related managers at all.
Only with FK attribute access.
That was a pragmatic decision as doing this for related managers could easily lead to fetching a lot more data from the database.

**Comment by iamjameswalters** [comment]
Sure, that makes sense, now that I think about it. Thanks for your input!
