### ISSUE TITLE
'prefetch_manager' causes unnecessary migrations

### ISSUE THREAD

**Issue by adamchainz** [tolomea/django-auto-prefetch#4]
After swapping to `auto_prefetch` classes one gets a migration with lots of migration operations like:

```python
migrations.AlterModelOptions(
    name='mymodel',
    options={'base_manager_name': 'prefetch_manager'},
),
migrations.AlterModelManagers(
    name='mymodel',
    managers=[
        ('prefetch_manager', django.db.models.manager.Manager()),
    ],
),
```

`prefetch_manager` isn't used directly, so can it not go?

**Comment by tolomea** [comment]
It needs to be the base manager so that objects fetched via a related set
do auto prefetching

**Comment by adamchainz** [comment]
Right of course
