### ISSUE TITLE
Multiple FK's to the same model

### ISSUE THREAD

**Issue by adamchainz** [tolomea/django-auto-prefetch#7]
If I have a model with two FK's to another one, would it make sense to fetch for both of them on attribute access of one of them?

**Comment by tolomea** [comment]
My gut feeling is no.
It can increase the query size (in result rows) which I've so far avoided.
Using one does not imply that they are likely to use the other, in contrast to the core premise here that if you access a field on one result row you are likely to access the same field on others.
And perhaps most importantly not doing so when it would help is just a +1 on the number of queries not a +N.
Granted when it does apply if the values totally overlap then it could half data transfer from that table. But conversely doing it when it doesn't apply would double data transfer if the values in the two columns are totally distinct.

**Comment by adamchainz** [comment]
I agree. Additionally Django doesn't currently make any provision for this, i.e. `prefetch_related('fk1', 'fk2')` does two queries when it could do one.

**Comment by adamchainz** [comment]
https://code.djangoproject.com/ticket/31666#ticket
