### ISSUE TITLE
Filter Nones from query

### ISSUE THREAD

**Issue by adamchainz** [tolomea/django-auto-prefetch#8]
Currently nullable FK's cause `id__in=[None, 1, None]` style queries. Good to filter them out before sending to DB to reduce SQL noise.

**Comment by tolomea** [comment]
Agree

**Comment by adamchainz** [comment]
This might actually be one for django as the prefetch is done with a plain `Prefetch('field_name')`

**Comment by adamchainz** [comment]
Also a Django ticket https://code.djangoproject.com/ticket/31667#ticket
