### ISSUE TITLE
Add system check for Model that its subclasses inherit its Meta class

### ISSUE THREAD

**Issue by adamchainz** [tolomea/django-auto-prefetch#9]
```python
class MyModel(auto_prefetch.Model):
    class Meta:
        some_option = "Woops"
```

This model won't use the base manager from `auto_prefetch.Model.Meta` - really it should have `class Meta(auto_prefetch.Model.Meta)`. A system check would protect against this.

**Comment by tolomea** [comment]
it'd be nice to have that and inheritance checks for managers and querysets generally available regardless of whether you are using auto prefetch
